### ISSUE TITLE
win64 py35

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [conda-forge/openmesh-feedstock#1]
Any reason win64 py35 is excluded from the build matrix?

Thanks for making this by the way; tried and failed several times myself.

**Comment by Korijn** [comment]
See https://github.com/conda-forge/staged-recipes/pull/1251

**Comment by Korijn** [comment]
Actually there's a link right beside the skip rule in the recipe: https://github.com/conda-forge/openmesh-feedstock/blob/master/recipe/meta.yaml#L22

**Comment by Korijn** [comment]
Looking at http://stackoverflow.com/questions/25957567/gcc-compiles-visual-studio-does-not and considering that our build fails only for VS2015, I'm thinking it's a bug in VC++ that was introduced in VS2013 that needs a work around...

We should be able to resolve this with a patch.

**Comment by xantares** [comment]
this is an upstream bug. closing

**Comment by Korijn** [comment]
No discussion? I would like to talk about the possibility of submitting a PR (upstream or through a patch).
